# Generated by Django 2.2.17 on 2020-12-28 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Уровень доступа')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('hash_view', models.CharField(blank=True, max_length=256)),
                ('access', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='libapp.AccessLevel', verbose_name='Категория доступа')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='libapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libapp.Category')),
                ('sequence_number', models.PositiveIntegerField(default=0, verbose_name='порядковый номер')),
                ('url_address', models.CharField(default='index', max_length=128, verbose_name='ссылка на страницу')),
            ],
            bases=('libapp.category',),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование документа')),
                ('doc_cover', models.ImageField(blank=True, upload_to='document_cover', verbose_name='Титульный лист')),
                ('short_desc', models.CharField(blank=True, max_length=60, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('doc_file', models.FileField(blank=True, upload_to='library', verbose_name='Файл документа')),
                ('acces_level', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='libapp.AccessLevel')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='libapp.Category', verbose_name='Категория доступа')),
            ],
        ),
    ]
