# Generated by Django 2.2.17 on 2020-12-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='url_address',
            field=models.CharField(blank=True, max_length=128, verbose_name='ссылка на страницу'),
        ),
    ]
