# Generated by Django 2.2.17 on 2020-12-30 19:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcategory',
            name='access',
        ),
        migrations.RemoveField(
            model_name='documentcategory',
            name='parent_category',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='DocumentCategory',
        ),
    ]
