# Generated by Django 2.2.17 on 2020-12-28 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('category_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libapp.Category')),
            ],
            bases=('libapp.category',),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование документа')),
                ('cover', models.ImageField(blank=True, upload_to='document_cover', verbose_name='Титульный лист')),
                ('short_desc', models.CharField(blank=True, max_length=60, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('doc_file', models.FileField(blank=True, upload_to='library', verbose_name='Файл документа')),
                ('time_publication', models.DateTimeField(auto_now_add=True, verbose_name='дата публикации статьи')),
                ('acces_level', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='libapp.AccessLevel')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='blogapp.BlogCategory', verbose_name='Категория блога')),
            ],
        ),
    ]
