# Generated by Django 2.2.17 on 2021-01-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='published_by',
            field=models.BooleanField(default=False, verbose_name='Статус публикации'),
        ),
    ]
