# Generated by Django 2.2.17 on 2021-01-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('blogapp', '0002_blog_published_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, upload_to='cover', verbose_name='Титульный лист'),
        ),
    ]
