# Generated by Django 2.2.17 on 2021-01-02 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='counteragent',
            name='full_name',
            field=models.CharField(default='', max_length=250, verbose_name='полное наименование'),
        ),
        migrations.AddField(
            model_name='counteragent',
            name='inn',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='counteragent',
            name='juridical_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juridical', to='authapp.Address'),
        ),
        migrations.AddField(
            model_name='counteragent',
            name='kpp',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='counteragent',
            name='physical_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical', to='authapp.Address'),
        ),
        migrations.AddField(
            model_name='counteragent',
            name='short_name',
            field=models.CharField(default='', max_length=150, verbose_name='наименование'),
        ),
        migrations.AddField(
            model_name='counteragent',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.PhoneNumber', verbose_name='номер телефона'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.PhoneNumber', verbose_name='номер телефона'),
        ),
    ]
