# Generated by Django 2.2.17 on 2021-01-02 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0002_auto_20210102_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteragent',
            name='base_counteragent',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
