# Generated by Django 2.2.17 on 2021-01-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0003_counteragent_base_counteragent'),
    ]

    operations = [
        migrations.AddField(
            model_name='counteragent',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='base_counteragent',
            field=models.BooleanField(default=False, verbose_name='Основная организация'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='full_name',
            field=models.CharField(default='', max_length=250, verbose_name='Полное наименование'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='juridical_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juridical',
                                    to='authapp.Address', verbose_name='Юридический адрес'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.PhoneNumber',
                                    verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='physical_address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physical',
                                    to='authapp.Address', verbose_name='Физический адрес'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='short_name',
            field=models.CharField(default='', max_length=150, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='counteragent',
            name='type_counteragent',
            field=models.CharField(
                choices=[('juridical_person', 'юридическое лицо'), ('physical_person', 'физическое лицо'),
                         ('separate_subdivision', 'обособленное подразделение'),
                         ('government_agency', 'государственный орган')], max_length=40,
                verbose_name='Тип контрагента'),
        ),
    ]
