# Generated by Django 2.2.17 on 2021-01-02 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20210102_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=3, null=True, verbose_name='код')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='страна')),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('coord_lon', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('coord_lat', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('weather_id', models.SmallIntegerField(max_length=4, verbose_name='')),
                ('weather_main', models.CharField(blank=True, max_length=20, null=True, verbose_name='')),
                ('weather_description', models.CharField(blank=True, max_length=40, null=True, verbose_name='')),
                ('weather_icon', models.CharField(blank=True, max_length=4, null=True, verbose_name='')),
                ('main_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('main_feels_like', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('main_temp_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('main_temp_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('main_pressure', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='')),
                ('main_humidity', models.SmallIntegerField(max_length=3, verbose_name='')),
                ('visibility', models.SmallIntegerField(max_length=6, verbose_name='')),
                ('wind_speed', models.SmallIntegerField(max_length=3, verbose_name='')),
                ('wind_deg', models.SmallIntegerField(max_length=3, verbose_name='')),
                ('city_id', models.SmallIntegerField(max_length=6, verbose_name='')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.Country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.SmallIntegerField(max_length=6, verbose_name='')),
                ('city_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='город')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.Country')),
            ],
        ),
    ]
