# Generated by Django 2.2.17 on 2021-01-02 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0005_city_country_weather'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.SmallIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weather',
            name='city_id',
            field=models.SmallIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main_humidity',
            field=models.SmallIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weather',
            name='visibility',
            field=models.SmallIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_id',
            field=models.SmallIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_deg',
            field=models.SmallIntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.SmallIntegerField(verbose_name=''),
        ),
    ]
