# Generated by Django 2.2.17 on 2021-01-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_auto_20210103_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='coord_lat',
            field=models.FloatField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weather',
            name='coord_lon',
            field=models.FloatField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main_feels_like',
            field=models.FloatField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main_pressure',
            field=models.FloatField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main_temp',
            field=models.FloatField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main_temp_max',
            field=models.FloatField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main_temp_min',
            field=models.FloatField(verbose_name=''),
        ),
    ]
