# Generated by Django 2.2.17 on 2021-01-03 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0011_auto_20210103_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weather',
            name='city_id',
        ),
        migrations.AddField(
            model_name='weather',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city', to='authapp.City', verbose_name=''),
        ),
    ]
