# Generated by Django 2.2.17 on 2021-01-03 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0012_auto_20210103_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.City'),
        ),
    ]
