# Generated by Django 2.2.17 on 2021-01-03 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_auto_20210103_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.City', verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='coord_lat',
            field=models.FloatField(verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='coord_lon',
            field=models.FloatField(verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.Country', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main_feels_like',
            field=models.FloatField(verbose_name='Ощущение'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main_humidity',
            field=models.SmallIntegerField(verbose_name='Влажность'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main_pressure',
            field=models.FloatField(verbose_name='Давление'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main_temp',
            field=models.FloatField(verbose_name='Температура'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main_temp_max',
            field=models.FloatField(verbose_name='Максимальная температура'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main_temp_min',
            field=models.FloatField(verbose_name='Минимальная температура'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='visibility',
            field=models.SmallIntegerField(verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_description',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Погодные условия'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_icon',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_id',
            field=models.SmallIntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_main',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Погодные явление'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_deg',
            field=models.SmallIntegerField(verbose_name='Направление ветра'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.SmallIntegerField(verbose_name='Скорость ветра'),
        ),
    ]
