# Generated by Django 2.2.17 on 2021-01-04 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('libapp', '0003_division'),
        ('authapp', '0016_auto_20210103_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='000', max_length=100, verbose_name='код должности')),
                ('name', models.CharField(max_length=100, verbose_name='должность')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divisions',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='libapp.Division',
                                   verbose_name='подразделение')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.Job',
                                          verbose_name='должность')),
            ],
        ),
    ]
