# Generated by Django 2.2.17 on 2021-01-04 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0017_job_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'мужской'), ('female', 'женский')], max_length=7, verbose_name='пол'),
        ),
        migrations.AddField(
            model_name='person',
            name='works',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='authapp.Work', verbose_name='занятость'),
        ),
    ]
