# Generated by Django 2.2.17 on 2021-01-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libapp', '0003_division'),
        ('authapp', '0019_auto_20210104_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='access_right',
        ),
        migrations.AddField(
            model_name='person',
            name='access_right',
            field=models.ManyToManyField(to='libapp.AccessLevel'),
        ),
    ]
