# Generated by Django 2.2.17 on 2021-01-04 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('authapp', '0021_auto_20210104_2118'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='corp_phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corp',
                                    to='authapp.PhoneNumber', verbose_name='корпоративный номер'),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell',
                                    to='authapp.PhoneNumber', verbose_name='номер телефона'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='number',
            field=models.CharField(max_length=15, verbose_name='Номер телефона'),
        ),
    ]
