# Generated by Django 2.2.17 on 2021-01-08 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0023_auto_20210104_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='city_id',
            field=models.IntegerField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='weather',
            name='main_humidity',
            field=models.IntegerField(verbose_name='Влажность'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='visibility',
            field=models.IntegerField(verbose_name='Видимость'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='weather_id',
            field=models.IntegerField(verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_deg',
            field=models.IntegerField(verbose_name='Направление ветра'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='wind_speed',
            field=models.IntegerField(verbose_name='Скорость ветра'),
        ),
    ]
