#command = '/home/xdamage/code/barkol/env/bin/gunicorn'
#pythonpath = '/home/xdamage/code/barkol/barkol'
bind = '127.0.0.1:8001'
workers = 3
user = 'xdamage'
timeout = 120
#limit_request_fields = 32000
#limit_request_field_size = 0
#raw_env = "DJANGO_SETTINGS_MODULE=edo.settings"
