# Generated by Django 2.2.17 on 2020-12-30 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('libapp', '0002_auto_20201230_2212'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название категории')),
                ('description', models.TextField(blank=True, verbose_name='Описание категории')),
                ('hash_view', models.CharField(blank=True, max_length=256)),
                ('access',
                 models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='libapp.AccessLevel',
                                   verbose_name='Категория доступа')),
                ('parent_category',
                 models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                   to='docapp.DocumentCategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Наименование документа')),
                ('doc_cover', models.ImageField(blank=True, upload_to='document_cover', verbose_name='Титульный лист')),
                ('short_desc', models.CharField(blank=True, max_length=60, verbose_name='Краткое описание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('doc_file', models.FileField(blank=True, upload_to='library', verbose_name='Файл документа')),
                ('acces_level',
                 models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='libapp.AccessLevel',
                                   verbose_name='Категория доступа')),
                ('author', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL,
                                             to=settings.AUTH_USER_MODEL, verbose_name='автор поста')),
                ('category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT,
                                               to='docapp.DocumentCategory', verbose_name='Категория документа')),
            ],
        ),
    ]
